# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
  
pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '11.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    # npm test
  displayName: 'npm install'

- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'wahaniya-corp(24cb7a23-a4cf-40e1-a530-af25a0a1060d)'
    KeyVaultName: 'kv-jpazureid'
    SecretsFilter: 'deploy-jpazureid-blog'

- script: |
    # thanks https://gist.github.com/stjohnjohnson/3d2388b2a7ba658cdcdaffa8cd874e50
    GITHUB_FINGERPRINT=nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8 

    mkdir -p ~/.ssh
    echo $Secret | base64 -d > ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa
    ssh-keyscan -H github.com >> ~/.ssh/known_hosts
    chmod 600 ~/.ssh/known_hosts

    echo Validating good known_hosts
    ssh-keygen -l -E sha256 -f ~/.ssh/known_hosts | grep $GITHUB_FINGERPRINT
    if [ $? = 1 ]; then exit 1; fi;

    git config --global user.email "jpazidbot@microsoft.com"
    git config --global user.name "jpazidbot"
    npm run deploy
  displayName: 'npm run deploy'
  env:
    Secret: $(deploy-jpazureid-blog)
