# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '11.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    # npm test
  displayName: 'npm install'

- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'wahaniya-corp(24cb7a23-a4cf-40e1-a530-af25a0a1060d)'
    KeyVaultName: 'kv-jpazureid'
    SecretsFilter: 'deploy-jpazureid-blog'

- script: |
    mkdir -p ~/.ssh
    echo $Secret | base64 -d > ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa
    ssh-keyscan -H github.com >> ~/.ssh/known_hosts
    chmod 600 ~/.ssh/known_hosts
    git config --global user.email "jpazidbot@microsoft.com"
    git config --global user.name "jpazidbot"
    git push origin master:testbranch
    # ssh-keygen -R github.com
    npm run deploy
  displayName: 'npm run deploy'
  env:
    Secret: $(deploy-jpazureid-blog)
